"""
Problem 002: Even Fibonacci Numbers
https://projecteuler.net/problem=002

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from utils.primes import sieve, is_prime, prime_factors
from utils.math_helpers import divisors, is_palindrome, digit_sum


def solve() -> int | str:
    fib = 1
    fib_minus_1 = 2
    fib_minus_2 = 1
    sum_of_evens = 2


    while sum_of_evens < 4000000:
        fib = fib_minus_1 + fib_minus_2
        if fib % 2 == 0:
            sum_of_evens += fib
        # print(fib)
        fib_minus_2 = fib_minus_1
        fib_minus_1 = fib


    return sum_of_evens





    pass


if __name__ == "__main__":
    print(solve())
